name: skyscape
description: "SkyScape is a weather app built with Flutter that uses the
  OpenWeatherApi to fetch and display weather data. The app provides users with
  detailed weather information, including the current temperature, weather
  condition, humidity, wind speed, and visibility. SkyScape offers a range of
  features, such as default location setting, location-based weather retrieval,
  theme switching, temperature conversion, and search functionality, to enhance
  the user experience and provide valuable weather insights."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  get: ^4.6.6
  get_server: ^1.2.1
  http: ^1.2.2
  is_first_run: ^1.0.0
  latlong2: ^0.9.1
  shared_preferences: ^2.3.1
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/city_list/owm_city_list.json
    - lib/assets/
  fonts:
    - family: GigaSans
      fonts:
        - asset: lib/assets/fonts/Locomotype  GigaSansBlack.otf
          weight: 900
        - asset: lib/assets/fonts/Locomotype  GigaSansBold.otf
          weight: 800
        - asset: lib/assets/fonts/Locomotype  GigaSansBold.otf
          weight: 700
        - asset: lib/assets/fonts/Locomotype  GigaSansSemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Locomotype  GigaSansMedium.otf
          weight: 500
        - asset: lib/assets/fonts/Locomotype  GigaSansRegular.otf
          weight: 400
        - asset: lib/assets/fonts/Locomotype  GigaSansLight.otf
          weight: 300
        - asset: lib/assets/fonts/Locomotype  GigaSansThin.otf
          weight: 200
