name: skyscape
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  get: ^4.6.6
  get_server: ^1.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/city_list/owm_city_list.json
  fonts:
    - family: GigaSans
      fonts:
        - asset: lib/assets/fonts/Locomotype  GigaSansBlack.otf
          weight: 900
        - asset: lib/assets/fonts/Locomotype  GigaSansBold.otf
          weight: 800
        - asset: lib/assets/fonts/Locomotype  GigaSansBold.otf
          weight: 700
        - asset: lib/assets/fonts/Locomotype  GigaSansSemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Locomotype  GigaSansMedium.otf
          weight: 500
        - asset: lib/assets/fonts/Locomotype  GigaSansRegular.otf
          weight: 400
        - asset: lib/assets/fonts/Locomotype  GigaSansLight.otf
          weight: 300
        - asset: lib/assets/fonts/Locomotype  GigaSansThin.otf
          weight: 200